### ISSUE TITLE
Empty profile

### ISSUE THREAD

**Issue by HugoCornu** [blikkhq/linkedin-extractor#1]
Hi,

I tried linkedin-extractor on a couple url and got empty profiles.

{"formattedName":"","headline":"","location":"","industry":"","numConnections":n
ull,"summary":"","experience":[],"skills":[],"urlResources":[],"education":[]}

**Comment by dennybritz** [comment]
Which URLs did you try? Are you running this locally or on AWS? Linkedin blocks AWS IPs.

**Comment by HugoCornu** [comment]
I tried locally

works on URL like:
https://www.linkedin.com/in/nawalmalek
doesnt work on URL like:
https://www.linkedin.com/profile/view?id=159091722

linkedin-extractor is not at fault here. Apprently the second type of url requieres to be authenticated to see the content
